name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm -w run build
      - name: Run tests
        run: pnpm -w run test || true
